name: QA Test Runner

on:
  repository_dispatch:
    types: [run-qa]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: âœ… Checkout QA Repo
      uses: actions/checkout@v4

    - name: â˜• Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: ğŸ”¹ Install dependencies
      run: mvn clean install
      shell: bash

    - name: ğŸ”¹ Run tests (Chrome Headless)
      run: mvn test -Dheadless=true
      shell: bash

    - name: ğŸ”¹ Generate Cucumber HTML Report
      run: mvn verify
      shell: bash

    - name: ğŸ“¤ Upload Cucumber HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-html-report
        path: target/cucumber-report-html




    - name: ğŸ“„ Generate HTML Report from JSON (only if JSON exists)
      run: mvn verify "-DgenerateReports=false"
      shell: bash

    - name: ğŸ” Debug report output
      run: |
        echo "ğŸ“ Isi folder target/jsonReports:"
        ls -la target/jsonReports || echo "Folder jsonReports not found"

        echo "ğŸ“„ Isi file cucumber.json:"
        if [ -f "target/jsonReports/cucumber.json" ]; then
          cat target/jsonReports/cucumber.json
        else
          echo "JSON file not found"
        fi
      shell: bash